DECLARE
  S_DATE SALES.SALES_DATE%TYPE;
  S_ORDERID SALES.ORDER_ID%TYPE:=1268;
  S_PRODUCTID SALES.PRODUCT_ID%TYPE;
  S_CUSTOMERID SALES.CUSTOMER_ID%TYPE;
  S_SALESPERSONID SALES.SALESPERSON_ID%TYPE;
  S_QUANTITY SALES.QUANTITY%TYPE;
  S_UNITPRICE SALES.UNIT_PRICE%TYPE;
  S_SALESAMOUNT SALES.SALES_AMOUNT%TYPE;
  S_TAXAMOUNT SALES.TAX_AMOUNT%TYPE;
  S_TOTALAMOUNT SALES.TOTAL_AMOUNT%TYPE;
BEGIN
  /*
  1) Write a program to fetch data from table SALES for a given orderid and
  display the data. (Use %TYPE when declaring variables).
  */
  DECLARE 
    S_DATE SALES.SALES_DATE%TYPE;
    S_ORDERID SALES.ORDER_ID%TYPE:=1268;
    S_PRODUCTID SALES.PRODUCT_ID%TYPE;
    S_CUSTOMERID SALES.CUSTOMER_ID%TYPE;
    S_SALESPERSONID SALES.SALESPERSON_ID%TYPE;
    S_QUANTITY SALES.QUANTITY%TYPE;
    S_UNITPRICE SALES.UNIT_PRICE%TYPE;
    S_SALESAMOUNT SALES.SALES_AMOUNT%TYPE;
    S_TAXAMOUNT SALES.TAX_AMOUNT%TYPE;
    S_TOTALAMOUNT SALES.TOTAL_AMOUNT%TYPE;
  BEGIN
    SELECT SALES_DATE,
      ORDER_ID,
      PRODUCT_ID,
      CUSTOMER_ID,
      SALESPERSON_ID,
      QUANTITY,
      UNIT_PRICE,
      SALES_AMOUNT,
      TAX_AMOUNT,
      TOTAL_AMOUNT
    INTO S_DATE,
      S_ORDERID,
      S_PRODUCTID,
      S_CUSTOMERID,
      S_SALESPERSONID,
      S_QUANTITY,
      S_UNITPRICE,
      S_SALESAMOUNT,
      S_TAXAMOUNT,
      S_TOTALAMOUNT
    FROM SALES
    WHERE ORDER_ID = S_ORDERID;
    
    DBMS_OUTPUT.PUT_LINE (S_DATE);
    DBMS_OUTPUT.PUT_LINE (S_ORDERID);
    DBMS_OUTPUT.PUT_LINE (S_PRODUCTID);
    DBMS_OUTPUT.PUT_LINE (S_CUSTOMERID);
    DBMS_OUTPUT.PUT_LINE (S_SALESPERSONID);
    DBMS_OUTPUT.PUT_LINE (S_QUANTITY);
    DBMS_OUTPUT.PUT_LINE (S_UNITPRICE);
    DBMS_OUTPUT.PUT_LINE (S_SALESAMOUNT);
    DBMS_OUTPUT.PUT_LINE (S_TAXAMOUNT);
    DBMS_OUTPUT.PUT_LINE (S_TOTALAMOUNT);
  END;
  
  /*
  2) Write a program to insert data into SALES table.
  */
  DECLARE
    S_DATE SALES.SALES_DATE%TYPE:=TO_DATE('18-02-2017','DD-MM-YYYY');
    S_ORDERID SALES.ORDER_ID%TYPE:=129512;
    S_PRODUCTID SALES.PRODUCT_ID%TYPE := 200;
    S_CUSTOMERID SALES.CUSTOMER_ID%TYPE := 12;
    S_SALESPERSONID SALES.SALESPERSON_ID%TYPE := 1000;
    S_QUANTITY SALES.QUANTITY%TYPE := 20;
    S_UNITPRICE SALES.UNIT_PRICE%TYPE := 30;
    S_SALESAMOUNT SALES.SALES_AMOUNT%TYPE := 600;
    S_TAXAMOUNT SALES.TAX_AMOUNT%TYPE :=60;
    S_TOTALAMOUNT SALES.TOTAL_AMOUNT%TYPE:=660;
  BEGIN
    INSERT INTO SALES(SALES_DATE, ORDER_ID, PRODUCT_ID, CUSTOMER_ID, SALESPERSON_ID,
                      QUANTITY, UNIT_PRICE, SALES_AMOUNT, TAX_AMOUNT, TOTAL_AMOUNT)
           VALUES (S_DATE, S_ORDERID, S_PRODUCTID, S_CUSTOMERID, S_SALESPERSONID,
                   S_QUANTITY, S_UNITPRICE, S_SALESAMOUNT, S_TOTALAMOUNT, S_TOTALAMOUNT);
  END;
  
  
  /*
  3) Write a program to update data in SALES table for a given orderid 
     (Change order amount to 100).
  */
  DECLARE
    S_ORDERID CONSTANT SALES.ORDER_ID%TYPE:=129512;
    S_AMOUNT CONSTANT SALES.TOTAL_AMOUNT%TYPE:=100;
  BEGIN
    UPDATE SALES SET TOTAL_AMOUNT = S_AMOUNT 
      WHERE ORDER_ID = S_ORDERID;
    COMMIT;
  END;
  
  /*
  4) Write a program to delete data from SALES table for a given orderid.
  */
  DECLARE
    S_ORDERID CONSTANT SALES.ORDER_ID%TYPE:=129512;
  BEGIN
    DELETE FROM SALES WHERE ORDER_ID = S_ORDERID;
    SELECT SYSDATE FROM DUAL;
    COMMIT;
  END;
  
END;
