CREATE OR REPLACE PROCEDURE ADD_CUSTOMER
(
  C_ID          IN NUMBER,
  C_FNAME       IN VARCHAR2,
  C_LNAME       IN VARCHAR2,
  C_MNAME       IN VARCHAR2,
  C_ADD1        IN VARCHAR2,
  C_ADD2        IN VARCHAR2,
  C_CITY        IN VARCHAR2,
  C_COUNTRY     IN VARCHAR2,
  C_DATE_ADDED  IN DATE,
  C_REGION      IN VARCHAR2
  )
  AS
  BEGIN
    INSERT INTO CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, 
                         MIDDLE_NAME, ADDRESS_LINE1, ADDRESS_LINE2,
                         CITY, COUNTRY, DATE_ADDED, REGION)
           VALUES(C_ID, C_FNAME, C_LNAME, 
                  C_MNAME, C_ADD1, C_ADD2,
                  C_CITY, C_COUNTRY, C_DATE_ADDED, C_REGION);
    COMMIT;
      DBMS_OUTPUT.PUT_LINE('Data successfuly Inserted');
    END ADD_CUSTOMER;
