CREATE OR REPLACE PROCEDURE SHOW_CUSTOMER
(
  C_ID          IN NUMBER,
  TCOUNT        OUT NUMBER
  )
  AS
    FNAME CUSTOMER.FIRST_NAME%TYPE;
  BEGIN
    SELECT FIRST_NAME INTO FNAME FROM CUSTOMER WHERE CUSTOMER_ID=C_ID;
    COMMIT;
    SELECT COUNT(1) INTO TCOUNT FROM CUSTOMER;
  END SHOW_CUSTOMER;

-- Execute

DECLARE
  TCOUNT NUMBER;
BEGIN
  SHOW_CUSTOMER(11, TCOUNT);
  DBMS_OUTPUT.PUT_LINE('TCOUNT: ' || TCOUNT);
END;
/