--------------------------------------------------------
--  File created - воскресенье-февраля-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "STUDENT"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"STANDARD_COST" NUMBER(10,2), 
	"COLOR" VARCHAR2(20 BYTE), 
	"LIST_PRICE" NUMBER(10,2), 
	"PRODUCT_SIZE" NUMBER(8,2), 
	"WEIGHT" NUMBER(10,2), 
	"PRODUCT_CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into STUDENT.PRODUCT
SET DEFINE OFF;
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('100','Mobile Cover','30',null,'35','10','100','Mobile');
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('200','Samsung F7100','80','BLACK','35','6','50','Mobile');
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('105','HTC 7800','70','BLACK','80','6','40','Mobile');
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('106','Microsoft Keyboard 7865','50','BLACK','60','3','20','Computer');
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('501','Microsoft Mouse 7863','30','GREY','40','1','25','Computer');
Insert into STUDENT.PRODUCT (PRODUCT_ID,PRODUCT_NAME,STANDARD_COST,COLOR,LIST_PRICE,PRODUCT_SIZE,WEIGHT,PRODUCT_CATEGORY) values ('101','iPhone','500','GOLD','600','6','20','Mobile');
