--------------------------------------------------------
--  File created - воскресенье-февраля-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALESPERSON
--------------------------------------------------------

  CREATE TABLE "STUDENT"."SALESPERSON" 
   (	"SALESPERSON_ID" NUMBER, 
	"JOB_TITLE" VARCHAR2(80 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"MIDDLE_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS_LINE1" VARCHAR2(80 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(80 BYTE), 
	"CITY" VARCHAR2(40 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"DATE_ADDED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into STUDENT.SALESPERSON
SET DEFINE OFF;
Insert into STUDENT.SALESPERSON (SALESPERSON_ID,JOB_TITLE,FIRST_NAME,LAST_NAME,MIDDLE_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,COUNTRY,DATE_ADDED) values ('1000','South Manager','PETER','MANN','R','4567 ASHFORDROAD',null,'CUMMING','USA',to_date('12.01.14','DD.MM.RR'));
Insert into STUDENT.SALESPERSON (SALESPERSON_ID,JOB_TITLE,FIRST_NAME,LAST_NAME,MIDDLE_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,COUNTRY,DATE_ADDED) values ('2000','North Manager','JOHN','KING','A','67 DUNWOODY ROAD',null,'LASVEGAS','USA',to_date('14.01.14','DD.MM.RR'));
Insert into STUDENT.SALESPERSON (SALESPERSON_ID,JOB_TITLE,FIRST_NAME,LAST_NAME,MIDDLE_NAME,ADDRESS_LINE1,ADDRESS_LINE2,CITY,COUNTRY,DATE_ADDED) values ('3000','East Manager','BOB','MORIS','A','679 GLENDRIGEDR',null,'FLORIDA','USA',to_date('14.02.14','DD.MM.RR'));
