--------------------------------------------------------
--  File created - воскресенье-февраля-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALES_HISTORY
--------------------------------------------------------

  CREATE TABLE "STUDENT"."SALES_HISTORY" 
   (	"SALES_DATE" DATE, 
	"ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER(5,0), 
	"SALESPERSON_ID" NUMBER(5,0), 
	"QUANTITY" NUMBER(4,0), 
	"UNIT_PRICE" NUMBER(10,2), 
	"SALES_AMOUNT" NUMBER(10,2), 
	"TAX_AMOUNT" NUMBER(10,2), 
	"TOTAL_AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into STUDENT.SALES_HISTORY
SET DEFINE OFF;
Insert into STUDENT.SALES_HISTORY (SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT) values (to_date('01.01.15','DD.MM.RR'),'1267','100','10','1000','2','20','40','4','44');
Insert into STUDENT.SALES_HISTORY (SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT) values (to_date('01.01.15','DD.MM.RR'),'1267','101','10','1000','2','30','60','6','66');
Insert into STUDENT.SALES_HISTORY (SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT) values (to_date('07.01.15','DD.MM.RR'),'1268','100','11','2000','10','30','300','30','330');
